[package]
name = "freecell-game"
version = "0.1.0"
edition = "2021"
description = "FreeCell solitaire game application"

[[bin]]
name = "game"
path = "src/main.rs"

[dependencies]
freecell-game-engine = { path = "../game-engine" }
