use freecell_game_engine::r#move::Move;

pub fn get_game_solution(seed: u64) -> Vec<Move> {
    match seed {
        1 => vec![
            Move::tableau_to_freecell(5, 0).unwrap(), // 1
            Move::tableau_to_freecell(5, 1).unwrap(), // 2
            Move::tableau_to_foundation(5, 0).unwrap(), // 3
            Move::freecell_to_foundation(1, 0).unwrap(), // 4
            Move::tableau_to_foundation(5, 1).unwrap(), // 5
            Move::tableau_to_freecell(6, 1).unwrap(), // 6
            Move::tableau_to_tableau(6, 5).unwrap(), // 7
            Move::tableau_to_freecell(6, 2).unwrap(), // 8
            Move::tableau_to_foundation(6, 2).unwrap(), // 9
            Move::tableau_to_foundation(2, 2).unwrap(), // 10
            Move::tableau_to_freecell(5, 3).unwrap(), // 11
            Move::tableau_to_tableau(5, 6).unwrap(), // 11
            Move::freecell_to_tableau(3, 6).unwrap(), // 11
            Move::tableau_to_tableau(2, 1).unwrap(), // 12
            Move::tableau_to_freecell(2, 3).unwrap(), // 13
            Move::tableau_to_tableau(2, 6).unwrap(), // 14
            Move::tableau_to_tableau(2, 6).unwrap(), // 15
            Move::freecell_to_tableau(1, 6).unwrap(), // 16
            Move::tableau_to_freecell(7, 1).unwrap(), // 17
            Move::tableau_to_tableau(7, 6).unwrap(), // 18
            Move::tableau_to_tableau(4, 6).unwrap(), // 19
            Move::tableau_to_tableau(4, 2).unwrap(), // 20
            Move::tableau_to_tableau(7, 2).unwrap(), // 21
            Move::tableau_to_foundation(7, 0).unwrap(), // 22
            Move::tableau_to_tableau(0, 5).unwrap(), // 23
            Move::tableau_to_tableau(0, 2).unwrap(), // 24
            Move::tableau_to_tableau(0, 4).unwrap(), // 25
            Move::tableau_to_foundation(0, 0).unwrap(), // 26
            Move::tableau_to_foundation(0, 1).unwrap(), // 27
            Move::tableau_to_foundation(7, 2).unwrap(), // 28
            Move::tableau_to_foundation(4, 1).unwrap(), // 29
            Move::tableau_to_foundation(4, 2).unwrap(), // 30
            Move::freecell_to_foundation(3, 1).unwrap(), // 31
            Move::tableau_to_foundation(7, 2).unwrap(), // 32
            Move::tableau_to_foundation(3, 2).unwrap(), // 33
            Move::tableau_to_tableau(3, 0).unwrap(), // 34
            Move::tableau_to_tableau(3, 7).unwrap(), // 35
            Move::tableau_to_freecell(1, 3).unwrap(), // 36
            Move::tableau_to_tableau(1, 7).unwrap(), // 36
            Move::freecell_to_tableau(3, 7).unwrap(), // 36
            Move::tableau_to_tableau(4, 3).unwrap(), // 37
            Move::tableau_to_foundation(4, 3).unwrap(), // 38
            Move::tableau_to_tableau(4, 6).unwrap(), // 39
            Move::tableau_to_tableau(1, 4).unwrap(), // 40
            Move::tableau_to_tableau(1, 3).unwrap(), // 41
            Move::tableau_to_foundation(1, 0).unwrap(), // 42
            Move::tableau_to_freecell(5, 3).unwrap(), // 43
            Move::tableau_to_tableau(5, 4).unwrap(), // 43
            Move::freecell_to_tableau(3, 4).unwrap(), // 43
            Move::tableau_to_tableau(1, 5).unwrap(), // 44
            Move::tableau_to_freecell(1, 3).unwrap(), // 45
            Move::tableau_to_foundation(1, 3).unwrap(), // 46
            Move::freecell_to_foundation(0, 3).unwrap(), // 47
            Move::freecell_to_foundation(2, 3).unwrap(), // 48
            Move::tableau_to_foundation(6, 3).unwrap(), // 49
            Move::tableau_to_foundation(6, 0).unwrap(), // 50
            Move::tableau_to_freecell(3, 0).unwrap(), // 51
            Move::tableau_to_freecell(3, 2).unwrap(), // 51
            Move::tableau_to_tableau(3, 5).unwrap(), // 51
            Move::freecell_to_tableau(2, 5).unwrap(), // 51
            Move::freecell_to_tableau(0, 5).unwrap(), // 51
            Move::tableau_to_freecell(3, 0).unwrap(), // 52
            Move::tableau_to_foundation(3, 1).unwrap(), // 53
            Move::tableau_to_foundation(2, 3).unwrap(), // 54
            Move::tableau_to_foundation(4, 1).unwrap(), // 55
            Move::tableau_to_foundation(2, 1).unwrap(), // 56
            Move::tableau_to_foundation(4, 2).unwrap(), // 57
            Move::tableau_to_foundation(6, 3).unwrap(), // 58
            Move::tableau_to_foundation(4, 1).unwrap(), // 59
            Move::tableau_to_freecell(0, 2).unwrap(), // 60
            Move::tableau_to_tableau(0, 4).unwrap(), // 60
            Move::freecell_to_tableau(2, 4).unwrap(), // 60
            Move::tableau_to_freecell(6, 2).unwrap(), // 61
            Move::freecell_to_tableau(1, 0).unwrap(), // 61
            Move::tableau_to_tableau(6, 0).unwrap(), // 61
            Move::freecell_to_tableau(3, 1).unwrap(), // 61
            Move::freecell_to_tableau(0, 1).unwrap(), // 61
            Move::tableau_to_freecell(6, 0).unwrap(), // 61
            Move::tableau_to_tableau(6, 4).unwrap(), // 61
            Move::tableau_to_freecell(6, 3).unwrap(), // 61
            Move::tableau_to_freecell(6, 1).unwrap(), // 61
            Move::tableau_to_foundation(6, 0).unwrap(), // 62
            Move::freecell_to_foundation(2, 0).unwrap(), // 63
            Move::tableau_to_foundation(7, 3).unwrap(), // 64
            Move::tableau_to_foundation(2, 2).unwrap(), // 65
            Move::tableau_to_foundation(7, 0).unwrap(), // 66
            Move::tableau_to_foundation(2, 1).unwrap(), // 67
            Move::tableau_to_foundation(0, 3).unwrap(), // 68
            Move::tableau_to_foundation(2, 2).unwrap(), // 69
            Move::freecell_to_foundation(0, 1).unwrap(), // 70
            Move::tableau_to_foundation(5, 3).unwrap(), // 71
            Move::tableau_to_foundation(0, 0).unwrap(), // 72
            Move::tableau_to_foundation(7, 2).unwrap(), // 73
            Move::tableau_to_foundation(5, 1).unwrap(), // 74
            Move::tableau_to_foundation(4, 2).unwrap(), // 75
            Move::tableau_to_foundation(3, 0).unwrap(), // 76
            Move::tableau_to_foundation(0, 3).unwrap(), // 77
            Move::freecell_to_foundation(3, 0).unwrap(), // 78
            Move::tableau_to_foundation(5, 2).unwrap(), // 79
            Move::tableau_to_foundation(4, 1).unwrap(), // 80
            Move::tableau_to_foundation(1, 3).unwrap(), // 81
            Move::freecell_to_foundation(1, 2).unwrap(), // 82
            Move::tableau_to_foundation(5, 1).unwrap(), // 83
            Move::tableau_to_foundation(4, 3).unwrap(), // 84
            Move::tableau_to_foundation(1, 0).unwrap(), // 85
        ],
        _ => panic!("No solution for this seed"),
    }
}
